# Generated by Django 3.1.2 on 2020-10-16 22:46

from django.db import migrations, models
from django.utils import timezone



def populate_db(apps, schema_editor):

	Group = apps.get_model('auth', 'Group')
	Tournament = apps.get_model('api', 'Tournament')
	Score = apps.get_model('api', 'Score')
	Drink = apps.get_model('api', 'Drink')

	Group.objects.bulk_create([
        Group(name=u'player'),
        Group(name=u'manager'),
        Group(name=u'drink_meister'),
    ])

	# Add tournaments
	
	t1Title = "Logan Disk Golf Championship"
	t1Description = "The big one."
	t1Holes = 18
	t1Participants = 150
	t1StartDate = "2021-10-1 12:00:00+00:00"
	
	t2Title = "Casual Get-together"
	t2Description ="Just some friends, getting together to play some disk golf!"
	t2Holes = 9
	t2Participants = 10
	t2StartDate = "2021-10-05 10:00:00+00:00"
	
	tournament1 = Tournament(name=t1Title,description=t1Description,holes=t1Holes,participants=t1Participants,startDate=t1StartDate)
	
	tournament2 = Tournament(name=t2Title,description=t2Description,holes=t2Holes,participants=t2Participants,startDate=t2StartDate)
	
	tournament1.save()
	tournament2.save()


	# Add Drinks
	
	d1Title = "Mango/Orange Screwdriver"
	d1Description = "A Delicious screwdriver made with premium vodka, orange juice, and Mango juice."
	d1Type = "hard"
	d1Price = 5.99
	
	d2Title = "Rum n' Coke"
	d2Description = "This drink expresses itself all in it's name."
	d2Type = "hard"
	d2Price = 5.99
	
	d3Title = "Sprite"
	d3Description = "1"
	d3Type = "soft"
	d3Price = 1.99
	
	d4Title = "Coca-Cola"
	d4Description = "2"
	d4Type = "soft"
	d4Price = 1.99
	
	d5Title = "Mountain Dew"
	d5Description = "3"
	d5Type = "soft"
	d5Price = 1.99
	
	drink1 = Drink(name=d1Title, description=d1Description, type=d1Type, price=d1Price)
	
	drink2 = Drink(name=d2Title, description=d2Description, type=d2Type, price=d2Price)
	
	drink3 = Drink(name=d3Title, description=d3Description, type=d3Type, price=d3Price)
	
	drink4 = Drink(name=d4Title, description=d4Description, type=d4Type, price=d4Price)
	
	drink5 = Drink(name=d5Title, description=d5Description, type=d5Type, price=d5Price)
	

	drink1.save()
	drink2.save()
	drink3.save()
	drink4.save()
	drink5.save()

class Migration(migrations.Migration):

	dependencies = [
		('api', '0001_initial'),
	]

	operations = [
		migrations.RunPython(populate_db)
	]
