# Generated by Django 3.2.9 on 2021-12-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tournament_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
