# Generated by Django 3.2.9 on 2021-12-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_populate2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pool',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
